[build]
  # Comando para construir tu proyecto
  command = "npm install && npm run build:netlify"
  # Directorio que se publicar치 (donde est치 el resultado de tu build)
  publish = "www"

[build.environment]
  # Versi칩n de Node.js requerida para tu proyecto
  NODE_VERSION = "16"

[plugins]
  # Ejemplo de c칩mo incluir un plugin de Netlify si es necesario
  package = "@netlify/angular-runtime"
